# Generated by Django 5.2.9 on 2026-01-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription_notes', '0002_livetranscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetranscription',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
