# Generated by Django 5.2.9 on 2026-01-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription_notes', '0003_alter_livetranscription_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload_transcription_files/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
