# Generated by Django 5.2.9 on 2026-01-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription_notes', '0004_uploadtranscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='source_file',
        ),
        migrations.AddField(
            model_name='notes',
            name='upload_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_entry', to='transcription_notes.uploadtranscription'),
        ),
    ]
