# Generated by Django 5.2.9 on 2026-01-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription_notes', '0005_remove_notes_source_file_notes_upload_source'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table=None,
        ),
    ]
