# Generated by Django 5.2.9 on 2026-01-16 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription_notes', '0006_alter_notes_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtranscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upload_Transcription', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
