# Generated by Django 5.2.9 on 2026-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription_notes', '0007_uploadtranscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('live', 'Live'), ('created', 'created'), ('manual', 'Manual')], max_length=20),
        ),
    ]
