# Generated by Django 5.2.9 on 2026-01-03 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('file', 'File'), ('live', 'Live')], max_length=10)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='transcriptions/')),
                ('transcript_text', models.TextField()),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transcriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
