# Generated by Django 5.2.9 on 2026-01-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='title',
            field=models.CharField(default='Untitled Note', max_length=225),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('live', 'Live')], max_length=20),
        ),
    ]
