# Generated by Django 5.2.9 on 2026-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_creditpurchase_credit_bundle_id_creditusagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpurchase',
            name='method',
            field=models.CharField(choices=[('online', 'Online'), ('wallet', 'Wallet')], default='online', max_length=20),
        ),
    ]
