# Generated by Django 5.2.9 on 2026-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_creditpurchase_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditpurchase',
            old_name='Credit_bundle_id',
            new_name='credit_bundle',
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='method',
            field=models.CharField(choices=[('online', 'Online'), ('wallet', 'Wallet')], db_index=True, default='online', max_length=20),
        ),
    ]
