# Generated by Django 5.2.9 on 2026-01-23 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_credit_bundle_id_creditpurchase_credit_bundle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='credit_bundle',
            field=models.ForeignKey(blank=True, db_column='Credit_bundle_id_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='subscriptions.creditbundle'),
        ),
    ]
