# Generated by Django 5.2.9 on 2026-01-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_creditpurchase_credit_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='credit_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='subscriptions.creditbundle'),
        ),
    ]
