# Generated by Django 5.2.6 on 2025-10-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersettings_alter_subscriptionhistory_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='Settings',
        ),
    ]
