# Generated by Django 5.2.6 on 2025-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_wallethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='purpose',
            field=models.CharField(choices=[('top-up', 'Top Up'), ('refund', 'Refund'), ('credit-purchase', 'Credit Purchase'), ('subscription', 'Subscription'), ('usage', 'Usage'), ('withdraw', 'Withdraw')], max_length=30),
        ),
    ]
