# Generated by Django 5.2.9 on 2026-01-14 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_wallethistory_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.IntegerField(default=0)),
                ('used_credits', models.IntegerField(default=0)),
                ('remaining_credits', models.IntegerField(default=0)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Credits',
                'db_table': 'user_credits',
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
