# Generated by Django 5.2.9 on 2026-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_usersubscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredits',
            name='last_purchase_date',
            field=models.DateField(auto_now=True),
        ),
    ]
