# Generated by Django 5.2.6 on 2025-11-29 11:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromodoroSettings',
            new_name='PomodoroSettings',
        ),
    ]
