# Generated by Django 5.2.6 on 2025-12-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_pomodorodailysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosettings',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
