# Generated by Django 5.2.6 on 2025-12-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0005_pomodorosettings_is_break'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorosettings',
            name='is_break',
        ),
    ]
