# Generated by Django 5.2.6 on 2025-12-15 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
