# Generated by Django 5.2.6 on 2025-12-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groupmessage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_messages/images/'),
        ),
    ]
